import { GetServerSidePropsContext } from 'next';
import { useTranslation } from 'next-i18next';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import Head from 'next/head';

const Blog = () => {
    const { t } = useTranslation(['common', 'button']);

    return (
        <>
            <Head>
                <title>{t('home.Home title')}</title>
                <meta name="description"
                    content="Generated by create next app"
                />
                <meta name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon"
                    href="/favicon.ico"
                />
            </Head>
            <main>
                <h1 className="text-3xl font-bold underline">
                    Hello world! Blog Page
                </h1>
            </main>
        </>
    );
};

export const getServerSideProps = async (ctx: GetServerSidePropsContext) => {
    return {
        props: {
            ...(await serverSideTranslations(ctx.locale ?? 'en', ['common', 'button'])),
        },
    };
};

export default Blog;
