import { useEffect } from 'react';
import { GetServerSidePropsContext } from 'next';
import { useRouter } from 'next/router';
import { useTranslation } from 'next-i18next';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import Head from 'next/head';
import { Button } from '@chakra-ui/react';
import { Bookmark } from '@icon-park/react';
import LocaleSwitcher from '@/components/LocaleSwitcher';

const Home = () => {
    const router = useRouter();
    const { t } = useTranslation(['common', 'button']);

    useEffect(() => {
        let dir = router.locale == 'fa' ? 'rtl' : 'ltr';
        let lang = router.locale == 'fa' ? 'fa' : 'en';
        document.querySelector('html')!.setAttribute('dir', dir);
        document.querySelector('html')!.setAttribute('lang', lang);
    }, [router.locale]);

    return (
        <>
            <Head>
                <title>{t('home.Home title')}</title>
                <meta name="description"
                    content="Generated by create next app"
                />
                <meta name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon"
                    href="/favicon.ico"
                />
            </Head>
            <main>
                <h1 className="text-3xl font-bold underline">
                    Hello world!
                </h1>
                <Button colorScheme='blue'>Button</Button>
                <Bookmark />
                <LocaleSwitcher />
                <br />
                <br />
                <h1>{t('home.Home title')}</h1>
                <span>{t('btn.text', { ns: 'button' })}</span>
            </main>
        </>
    );
};

export const getServerSideProps = async (ctx: GetServerSidePropsContext) => {
    return {
        props: {
            ...(await serverSideTranslations(ctx.locale ?? 'en', ['common', 'button'])),
        },
    };
};

export default Home;
