import Head from 'next/head';
import { Button } from '@chakra-ui/react';
import { Bookmark } from '@icon-park/react';

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description"
                    content="Generated by create next app"
                />
                <meta name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon"
                    href="/favicon.ico"
                />
            </Head>
            <main>
                <h1 className="text-3xl font-bold underline">
                    Hello world!
                </h1>
                <Button colorScheme='blue'>Button</Button>
                <Bookmark />
            </main>
        </>
    );
}
